### ISSUE TITLE
[Feature request]Would you edit this code for allow to use self-define path ?

### ISSUE THREAD

**Issue by egg1234** [tina-hello/doh-cf-pages#1]
For example : https://yourdoh.pages.dev/self-define-doh-path

Because this code just fix to no path and just use https://yourdoh.pages.dev

The no path URL for firefox and chrome is fine but windows 11 can't use no path URL in DoH

Thank you!

**Comment by tina-hello** [comment]
Interesting, I believe renaming the index.js should be enough, but I'll try checking it first, once proven I'll update the readme, or if it doesn't work, I'll figure out how to accept path and update the code

**Comment by tina-hello** [comment]
Yep, confirmed, either just rename the index.js yourself or use the https://github.com/tina-hello/doh-cf-pages/tree/testpath branch which will deploy to `dns-query` path. Thanks for the info!
