### ISSUE TITLE
Would you release a new repo for echo user wan ip for use CF-pages?

### ISSUE THREAD

**Issue by egg1234** [tina-hello/doh-cf-pages#2]
For example: curl https://your-ip.pages.dev

It will echo user wan ip like:
172.172.172.172

This echo is very helpful for DDNS update. 

const clientIP = request.headers.get("CF-Connecting-IP")
return new Response(clientIP);

--------------------------------------------------------------------------------------
If other new CF-pages repo for echo user ip geo data will be great, 
For example: curl https://your-ip-geo.pages.dev
  
It will echo user wan ip geo data like:
Public IP: 172.172.172.172
ASN: 396982
ISP: Google Cloud
Country: US
City: The Dalles
Region: Oregon
Latitude, Longitude: 45.59990,-121.18710
Postal Code: 97058
Timezone: America/Los_Angeles
User Agent: curl/7.81.0

 {
  const clientUA = request.headers.get('User-Agent');
  const clientIP = request.headers.get('CF-Connecting-IP');
  const clientASN = request.cf.asn;
  const clientISP = request.cf.asOrganization;
  const clientCO = request.cf.country;
  const clientCI = request.cf.city;
  const clientRE = request.cf.region;
  const clientLAT = request.cf.latitude;
  const clientLON = request.cf.longitude;
  const clientPC = request.cf.postalCode;
  const clientTZ = request.cf.timezone;

  return new Response("Public IP: " + clientIP + "\n" + 
  "ASN: " + clientASN + "\n" + 
  "ISP: " + clientISP + "\n" + 
  "Country: " + clientCO + "\n" + 
  "City: " + clientCI + "\n" + 
  "Region: " + clientRE + "\n" + 
  "Latitude, Longitude: " + clientLAT + "," + clientLON + "\n" + 
  "Postal Code: " + clientPC + "\n" + 
  "Timezone: " + clientTZ + "\n" + 
  "User Agent: " + clientUA + "\n"
  );
}

**Comment by tina-hello** [comment]
TIL, that's seriously neat. https://github.com/tina-hello/ip-cf-pages
