### ISSUE TITLE
Fault notification

### ISSUE THREAD

**Issue by laorent** [tina-hello/doh-cf-pages#4]
"After deploying your page and using the same path as youraddress.pages.dev/dns-query, I found that it is no longer accessible."

**Comment by tina-hello** [comment]
If you deployed the `main` branch, the usable path is `https://yourpagespath.dev/`, if you deployed the `testpath`, then you'll get `https://yourpagespath.pages.dev/dns-query`, you may need to add a commit to trigger redeployment if you change the branch after deployment. If it still doesn't work, install https://github.com/ameshkov/dnslookup and share the output of

    dnslookup google.com https://yourpagespath.pages.dev/dns-query
    
 and 
 
     dnslookup google.com https://yourpagespath.pages.dev/
